<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Events\Common.Events.csproj" />
    <ProjectReference Include="..\Common.RabbitMQ.Configuration\Common.RabbitMQ.Configuration.csproj" />
    <ProjectReference Include="..\Common.RabbitMQ\Common.RabbitMQ.csproj" />
    <ProjectReference Include="..\Contracts\Employees.Contracts\Employees.Contracts.csproj" />
    <ProjectReference Include="..\Messaging\Messaging.Prism\Messaging.Prism.csproj" />
  </ItemGroup>

</Project>
